version: "3.9"

services:
  app:
    build: .
    ports:
      - "8020:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    volumes:
      - ./data:/app/data                          # Database files
      - ./logs:/app/logs                          # Log files
      - ./resources:/app/resources                
    restart: unless-stopped

