"""
Report i18n - Translation dictionaries for HTML report generation.

Provides English and Chinese translations for all report text content.
"""

from typing import Dict, Any

# Supported languages
SUPPORTED_LANGUAGES = ["en", "zh"]
DEFAULT_LANGUAGE = "en"

TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "en": {
        # Language
        "lang": "en",
        
        # Header labels
        "report_type": "Report Type",
        "generated": "Generated",
        "strategy": "Strategy",
        "symbol": "Symbol",
        "period": "Period",
        
        # Report types
        "backtest": "Backtest",
        "portfolio": "Portfolio",
        "walkforward": "Walk-Forward",
        "comparison": "Comparison",
        
        # Tabs
        "tab_overview": "Overview",
        "tab_charts": "Charts",
        "tab_trades": "Trades",
        "tab_parameters": "Parameters",
        "tab_deep_analysis": "Deep Analysis",
        "tab_ai_analysis": "AI Analysis",
        
        # Performance metrics
        "final_value": "Final Value",
        "total_return": "Total Return",
        "sharpe_ratio": "Sharpe Ratio",
        "max_drawdown": "Max Drawdown",
        "total_trades": "Total Trades",
        "win_rate": "Win Rate",
        "profit_factor": "Profit Factor",
        "sqn": "SQN",
        
        # Section titles
        "performance_overview": "Performance Overview",
        "annual_returns": "Annual Returns",
        "equity_curve": "Equity Curve",
        "drawdown": "Drawdown",
        "strategy_chart": "Strategy Chart",
        "trade_summary": "Trade Summary",
        "backtest_config": "Backtest Configuration",
        "strategy_params": "Strategy Parameters",
        "monthly_returns": "Monthly Returns Heatmap",
        "rolling_sharpe": "Rolling Sharpe Ratio",
        "returns_distribution": "Returns Distribution",
        "drawdown_analysis": "Drawdown Analysis",
        "benchmark_comparison": "Benchmark Comparison",
        "ai_analysis": "AI Analysis",
        
        # Table headers
        "year": "Year",
        "return": "Return",
        "entry_date": "Entry Date",
        "exit_date": "Exit Date",
        "type": "Type",
        "size": "Size",
        "entry_price": "Entry Price",
        "exit_price": "Exit Price",
        "pnl": "P&L",
        "return_pct": "Return",
        "metric": "Metric",
        "correlation": "Correlation",
        "beta": "Beta",
        "alpha": "Alpha",
        
        # Trade summary
        "winning_trades": "Winning Trades",
        "losing_trades": "Losing Trades",
        "no_trade_data": "No trade data available",
        
        # Distribution stats
        "mean": "Mean",
        "std_dev": "Std Dev",
        "skewness": "Skewness",
        "kurtosis": "Kurtosis",
        "var_95": "VaR (95%)",
        "cvar_95": "CVaR (95%)",
        "avg_drawdown": "Avg Drawdown",
        
        # Config labels
        "start_date": "Start Date",
        "end_date": "End Date",
        "initial_cash": "Initial Cash",
        "commission": "Commission",
        "stake": "Stake",
        
        # Footer
        "footer_generated_by": "Generated by Backtrader Trading Platform",
        "footer_report_id": "Report ID",
        
        # Misc
        "no_data": "N/A",
        "trading_report": "Trading Report",
    },
    "zh": {
        # 语言
        "lang": "zh",
        
        # 标题标签
        "report_type": "报告类型",
        "generated": "生成时间",
        "strategy": "策略",
        "symbol": "标的",
        "period": "周期",
        
        # 报告类型
        "backtest": "回测",
        "portfolio": "组合",
        "walkforward": "滚动优化",
        "comparison": "对比",
        
        # 标签页
        "tab_overview": "概览",
        "tab_charts": "图表",
        "tab_trades": "交易记录",
        "tab_parameters": "参数配置",
        "tab_deep_analysis": "深度分析",
        "tab_ai_analysis": "AI 分析",
        
        # 绩效指标
        "final_value": "最终价值",
        "total_return": "总收益率",
        "sharpe_ratio": "夏普比率",
        "max_drawdown": "最大回撤",
        "total_trades": "总交易次数",
        "win_rate": "胜率",
        "profit_factor": "盈亏比",
        "sqn": "系统质量指数",
        
        # 区块标题
        "performance_overview": "绩效概览",
        "annual_returns": "年度收益",
        "equity_curve": "资金曲线",
        "drawdown": "回撤",
        "strategy_chart": "策略图表",
        "trade_summary": "交易汇总",
        "backtest_config": "回测配置",
        "strategy_params": "策略参数",
        "monthly_returns": "月度收益热力图",
        "rolling_sharpe": "滚动夏普比率",
        "returns_distribution": "收益率分布",
        "drawdown_analysis": "回撤分析",
        "benchmark_comparison": "基准对比",
        "ai_analysis": "AI 分析",
        
        # 表格标题
        "year": "年份",
        "return": "收益率",
        "entry_date": "入场日期",
        "exit_date": "出场日期",
        "type": "类型",
        "size": "数量",
        "entry_price": "入场价格",
        "exit_price": "出场价格",
        "pnl": "盈亏",
        "return_pct": "收益率",
        "metric": "指标",
        "correlation": "相关性",
        "beta": "贝塔",
        "alpha": "阿尔法",
        
        # 交易汇总
        "winning_trades": "盈利交易",
        "losing_trades": "亏损交易",
        "no_trade_data": "暂无交易数据",
        
        # 分布统计
        "mean": "均值",
        "std_dev": "标准差",
        "skewness": "偏度",
        "kurtosis": "峰度",
        "var_95": "VaR (95%)",
        "cvar_95": "CVaR (95%)",
        "avg_drawdown": "平均回撤",
        
        # 配置标签
        "start_date": "开始日期",
        "end_date": "结束日期",
        "initial_cash": "初始资金",
        "commission": "手续费",
        "stake": "下注数量",
        
        # 页脚
        "footer_generated_by": "由 Backtrader 交易平台生成",
        "footer_report_id": "报告 ID",
        
        # 其他
        "no_data": "暂无数据",
        "trading_report": "交易报告",
    }
}


def get_translations(language: str = "en") -> Dict[str, str]:
    """
    Get translation dictionary for the specified language.
    
    Args:
        language: Language code ("en" or "zh")
        
    Returns:
        Translation dictionary
    """
    if language not in SUPPORTED_LANGUAGES:
        language = DEFAULT_LANGUAGE
    return TRANSLATIONS[language]


def get_report_type_name(report_type: str, language: str = "en") -> str:
    """
    Get localized report type name.
    
    Args:
        report_type: Report type key (backtest, portfolio, etc.)
        language: Language code
        
    Returns:
        Localized report type name
    """
    translations = get_translations(language)
    return translations.get(report_type, report_type.capitalize())


__all__ = [
    "SUPPORTED_LANGUAGES",
    "DEFAULT_LANGUAGE",
    "TRANSLATIONS",
    "get_translations",
    "get_report_type_name",
]
