"""
Chart Generator - Generates backtest charts from Cerebro instances.

This module separates chart generation logic from backtest execution,
providing a clean interface for creating and saving chart images.
"""

from typing import Optional
from pathlib import Path
import logging

import backtrader as bt

logger = logging.getLogger(__name__)


class ChartGenerator:
    """
    Generates and saves charts from completed backtests.

    Handles:
    - Matplotlib backend configuration for headless operation
    - Suppression of GUI popup attempts
    - Chart sizing and saving
    - Error handling and cleanup

    Usage:
        generator = ChartGenerator(cerebro)
        plot_url = generator.save(Path("charts/backtest_001.png"))
    """

    # Default chart settings
    DEFAULT_WIDTH = 18
    DEFAULT_HEIGHT = 10
    DEFAULT_DPI = 150
    DEFAULT_STYLE = "candlestick"

    def __init__(
        self,
        cerebro: bt.Cerebro,
        width: float = DEFAULT_WIDTH,
        height: float = DEFAULT_HEIGHT,
        dpi: int = DEFAULT_DPI,
        style: str = DEFAULT_STYLE
    ):
        """
        Initialize the chart generator.

        Args:
            cerebro: Completed Cerebro instance
            width: Chart width in inches
            height: Chart height in inches
            dpi: Dots per inch for saved image
            style: Chart style (candlestick, bar, line)
        """
        self.cerebro = cerebro
        self.width = width
        self.height = height
        self.dpi = dpi
        self.style = style

    def save(self, save_path: Path) -> Optional[str]:
        """
        Generate and save the chart to a file.

        Configures matplotlib for headless operation and handles
        all aspects of chart generation and saving.

        Args:
            save_path: Path to save the chart image

        Returns:
            URL path for accessing the chart, or None if generation fails
        """
        if save_path is None:
            return None

        try:
            # Ensure parent directory exists
            save_path.parent.mkdir(parents=True, exist_ok=True)

            # Configure matplotlib for headless operation
            self._configure_matplotlib()

            # Generate and save the chart
            self._generate_and_save(save_path)

            logger.info(f"Chart saved to {save_path}")

            # Return URL path for UI access
            return f"/images/{save_path.name}"

        except Exception as e:
            logger.warning(f"Failed to generate chart: {e}")
            self._cleanup_matplotlib()
            return None

    def _configure_matplotlib(self):
        """Configure matplotlib for headless operation."""
        import matplotlib
        matplotlib.use('Agg', force=True)

        import matplotlib.pyplot as plt
        plt.ioff()  # Turn off interactive mode
        plt.switch_backend('Agg')

    def _generate_and_save(self, save_path: Path):
        """Generate the chart and save to file."""
        import matplotlib.pyplot as plt

        # Suppress plt.show() calls from Backtrader
        original_show = plt.show
        plt.show = lambda *args, **kwargs: None

        try:
            # Generate plots
            figures = self.cerebro.plot(
                style=self.style,
                volume=False,
                iplot=False
            )

            # Get the first figure
            first_fig = self._get_first_figure(figures)

            if first_fig:
                # Configure figure size
                first_fig.set_size_inches(self.width, self.height)

                # Save with tight bounding box
                first_fig.savefig(
                    save_path,
                    bbox_inches='tight',
                    dpi=self.dpi
                )

                # Close the figure to free memory
                plt.close(first_fig)
            else:
                logger.warning("No figure generated by Cerebro.plot()")

        finally:
            # Restore original plt.show
            plt.show = original_show

            # Close all remaining figures
            plt.close('all')

    def _get_first_figure(self, figures):
        """Extract the first figure from Cerebro.plot() result."""
        if figures and len(figures) > 0:
            if figures[0] and len(figures[0]) > 0:
                return figures[0][0]
        return None

    def _cleanup_matplotlib(self):
        """Clean up matplotlib resources."""
        try:
            import matplotlib.pyplot as plt
            plt.close('all')
        except Exception:
            pass

    def generate_equity_curve_chart(
        self,
        equity_curve: dict,
        save_path: Path,
        title: str = "Portfolio Equity Curve"
    ) -> Optional[str]:
        """
        Generate a standalone equity curve chart.

        Args:
            equity_curve: Dictionary mapping dates to portfolio values
            save_path: Path to save the chart
            title: Chart title

        Returns:
            URL path for accessing the chart, or None if generation fails
        """
        if not equity_curve:
            return None

        try:
            self._configure_matplotlib()

            import matplotlib.pyplot as plt
            import matplotlib.dates as mdates
            from datetime import datetime

            # Parse dates and values
            dates = []
            values = []
            for date_str, value in sorted(equity_curve.items()):
                try:
                    if isinstance(date_str, str):
                        dates.append(datetime.fromisoformat(date_str))
                    else:
                        dates.append(date_str)
                    values.append(value)
                except (ValueError, TypeError):
                    continue

            if not dates:
                return None

            # Create figure
            fig, ax = plt.subplots(figsize=(self.width, self.height // 2))

            # Plot equity curve
            ax.plot(dates, values, 'b-', linewidth=1.5, label='Portfolio Value')
            ax.fill_between(dates, values, alpha=0.3)

            # Configure axes
            ax.set_title(title, fontsize=14, fontweight='bold')
            ax.set_xlabel('Date')
            ax.set_ylabel('Portfolio Value ($)')
            ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
            ax.xaxis.set_major_locator(mdates.MonthLocator(interval=3))
            plt.xticks(rotation=45)

            # Add grid
            ax.grid(True, alpha=0.3)
            ax.legend()

            # Ensure parent directory exists
            save_path.parent.mkdir(parents=True, exist_ok=True)

            # Save
            fig.savefig(save_path, bbox_inches='tight', dpi=self.dpi)
            plt.close(fig)

            logger.info(f"Equity curve chart saved to {save_path}")
            return f"/images/{save_path.name}"

        except Exception as e:
            logger.warning(f"Failed to generate equity curve chart: {e}")
            self._cleanup_matplotlib()
            return None


__all__ = ["ChartGenerator"]
